name: Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - .gitignore
    branches-ignore:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Test
    runs-on: macos-15
    timeout-minutes: 15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.4.app/Contents/Developer"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run Test
        run: |
          xcodebuild test \
            -scheme xcstrings-migrator-Package \
            -destination "platform=macOS,arch=arm64" \
            -derivedDataPath DerivedData \
            -resultBundlePath TestResults/result_bundle | \
            xcbeautify && exit ${PIPESTATUS[0]}
